- name: Install and run paideia-offchain services
  hosts: paideia_offchain
  remote_user: "{{ ssh_user }}"

- name: paideia offchain bots
  ansible.builtin.import_playbook: paideia-offchain-template.yml
  vars:
    project: im.paideia

- name: anetabtc offchain bots
  ansible.builtin.import_playbook: paideia-offchain-template.yml
  vars:
    project: io.anetabtc

- name: ergogames offchain bots
  ansible.builtin.import_playbook: paideia-offchain-template.yml
  vars:
    project: io.ergogames