- name: Install and run paideia-api services
  hosts: paideia_api
  remote_user: "{{ ssh_user }}"

  tasks:
  - name: git clone repo for paideia
    ansible.builtin.git:
      repo: https://github.com/paideiadao/paideia-api.git
      dest: /opt/paideia/paideia-api
      single_branch: yes
      version: dev

  - name: write .env file
    ansible.builtin.template:
      src: ./.env.j2
      dest: /opt/paideia/paideia-api/.env

  - name: create paideia docker network
    community.docker.docker_network:
      name: p-net

  - name: spin up docker containers
    environment: "{{ env }}"
    ansible.builtin.docker_compose:
      project_src: /opt/paideia/paideia-api